<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Role::truncate();
        // Permission::truncate();
        DB::table('roles')->delete();
        DB::table('permissions')->delete();
        Permission::create(['name' => 'Manage User']);
        Permission::create(['name' => 'Create User']);
        Permission::create(['name' => 'Edit User']);
        Permission::create(['name' => 'Delete User']);
        Permission::create(['name' => 'Manage Ip']);
        Permission::create(['name' => 'Create Ip']);
        Permission::create(['name' => 'Edit Ip']);
        Permission::create(['name' => 'Delete Ip']);
        Permission::create(['name' => 'Manage Role']);
        Permission::create(['name' => 'Create Role']);
        Permission::create(['name' => 'Delete Role']);
        Permission::create(['name' => 'Edit Role']);
        Permission::create(['name' => 'Manage Branch']);
        Permission::create(['name' => 'Create Branch']);
        Permission::create(['name' => 'Edit Branch']);
        Permission::create(['name' => 'Delete Branch']);
        Permission::create(['name' => 'Manage Department']);
        Permission::create(['name' => 'Create Department']);
        Permission::create(['name' => 'Edit Department']);
        Permission::create(['name' => 'Delete Department']);
        Permission::create(['name' => 'Manage Designation']);
        Permission::create(['name' => 'Create Designation']);
        Permission::create(['name' => 'Edit Designation']);
        Permission::create(['name' => 'Delete Designation']);
        Permission::create(['name' => 'Manage Document Type']);
        Permission::create(['name' => 'Create Document Type']);
        Permission::create(['name' => 'Edit Document Type']);
        Permission::create(['name' => 'Delete Document Type']);
        Permission::create(['name' => 'Manage Allowance Option']);
        Permission::create(['name' => 'Create Allowance Option']);
        Permission::create(['name' => 'Edit Allowance Option']);
        Permission::create(['name' => 'Delete Allowance Option']);
        Permission::create(['name' => 'Manage Leave Type']);
        Permission::create(['name' => 'Create Leave Type']);
        Permission::create(['name' => 'Edit Leave Type']);
        Permission::create(['name' => 'Delete Leave Type']);
        Permission::create(['name' => 'Manage Termination Type']);
        Permission::create(['name' => 'Create Termination Type']);
        Permission::create(['name' => 'Edit Termination Type']);
        Permission::create(['name' => 'Delete Termination Type']);
        Permission::create(['name' => 'Manage Award Type']);
        Permission::create(['name' => 'Create Award Type']);
        Permission::create(['name' => 'Edit Award Type']);
        Permission::create(['name' => 'Delete Award Type']);
        Permission::create(['name' => 'Manage Training Type']);
        Permission::create(['name' => 'Create Training Type']);
        Permission::create(['name' => 'Edit Training Type']);
        Permission::create(['name' => 'Delete Training Type']);
        Permission::create(['name' => 'Manage Job Category']);
        Permission::create(['name' => 'Create Job Category']);
        Permission::create(['name' => 'Edit Job Category']);
        Permission::create(['name' => 'Delete Job Category']);
        Permission::create(['name' => 'Manage Job Stage']);
        Permission::create(['name' => 'Create Job Stage']);
        Permission::create(['name' => 'Edit Job Stage']);
        Permission::create(['name' => 'Delete Job Stage']);
        Permission::create(['name' => 'Manage Employee']);
        Permission::create(['name' => 'Create Employee']);
        Permission::create(['name' => 'Edit Employee']);
        Permission::create(['name' => 'Delete Employee']);
        Permission::create(['name' => 'Manage Award']);
        Permission::create(['name' => 'Create Award']);
        Permission::create(['name' => 'Edit Award']);
        Permission::create(['name' => 'Delete Award']);
        Permission::create(['name' => 'Manage Transfer']);
        Permission::create(['name' => 'Create Transfer']);
        Permission::create(['name' => 'Edit Transfer']);
        Permission::create(['name' => 'Delete Transfer']);
        Permission::create(['name' => 'Manage Resignation']);
        Permission::create(['name' => 'Create Resignation']);
        Permission::create(['name' => 'Edit Resignation']);
        Permission::create(['name' => 'Delete Resignation']);
        Permission::create(['name' => 'Manage Travel']);
        Permission::create(['name' => 'Create Travel']);
        Permission::create(['name' => 'Edit Travel']);
        Permission::create(['name' => 'Delete Travel']);
        Permission::create(['name' => 'Manage Promotion']);
        Permission::create(['name' => 'Create Promotion']);
        Permission::create(['name' => 'Edit Promotion']);
        Permission::create(['name' => 'Delete Promotion']);
        Permission::create(['name' => 'Manage Termination']);
        Permission::create(['name' => 'Create Termination']);
        Permission::create(['name' => 'Edit Termination']);
        Permission::create(['name' => 'Delete Termination']);
        Permission::create(['name' => 'Manage Set Salary']);
        Permission::create(['name' => 'Create Set Salary']);
        Permission::create(['name' => 'Manage Payroll']);
        Permission::create(['name' => 'Manage Generate Salary']);
        Permission::create(['name' => 'Create Generate Salary']);
        Permission::create(['name' => 'Show Generate Salary']);
        Permission::create(['name' => 'Manage Loan']);
        Permission::create(['name' => 'Create Loan']);
        Permission::create(['name' => 'Manage Announcement']);
        Permission::create(['name' => 'Create Announcement']);
        Permission::create(['name' => 'Edit Announcement']);
        Permission::create(['name' => 'Delete Announcement']);
        Permission::create(['name' => 'Manage Leave']);
        Permission::create(['name' => 'Create Leave']);
        Permission::create(['name' => 'Edit Leave']);
        Permission::create(['name' => 'Delete Leave']);
        Permission::create(['name' => 'Manage Loan Type']);
        Permission::create(['name' => 'Create Loan Type']);
        Permission::create(['name' => 'Edit Loan Type']);
        Permission::create(['name' => 'Delete Loan Type']);
        Permission::create(['name' => 'Manage Meeting']);
        Permission::create(['name' => 'Create Meeting']);
        Permission::create(['name' => 'Edit Meeting']);
        Permission::create(['name' => 'Delete Meeting']);
        Permission::create(['name' => 'Manage Attendance']);
        Permission::create(['name' => 'Create Attendance']);
        Permission::create(['name' => 'Edit Attendance']);
        Permission::create(['name' => 'Delete Attendance']);
        Permission::create(['name' => 'Manage Trainer']);
        Permission::create(['name' => 'Create Trainer']);
        Permission::create(['name' => 'Edit Trainer']);
        Permission::create(['name' => 'Delete Trainer']);
        Permission::create(['name' => 'Manage Training']);
        Permission::create(['name' => 'Create Training']);
        Permission::create(['name' => 'Edit Training']);
        Permission::create(['name' => 'Delete Training']);
        Permission::create(['name' => 'Show Training']);
        Permission::create(['name' => 'Manage Performance']);
        Permission::create(['name' => 'Create Performance']);
        Permission::create(['name' => 'Edit Performance']);
        Permission::create(['name' => 'Delete Performance']);
        Permission::create(['name' => 'Manage Performance Criteria']);
        Permission::create(['name' => 'Create Performance Criteria']);
        Permission::create(['name' => 'Edit Performance Criteria']);
        Permission::create(['name' => 'Delete Performance Criteria']);
        Permission::create(['name' => 'Manage Performance Metric']);
        Permission::create(['name' => 'Create Performance Metric']);
        Permission::create(['name' => 'Edit Performance Metric']);
        Permission::create(['name' => 'Delete Performance Metric']);
        Permission::create(['name' => 'Show Loan']);
        Permission::create(['name' => 'Show Set Salary']);
        Permission::create(['name' => 'Show Leave']);
        Permission::create(['name' => 'Show Attendance']);
        Permission::create(['name' => 'Show Trainer']);
        Permission::create(['name' => 'Show Meeting']);
        Permission::create(['name' => 'Show Performance']);
        Permission::create(['name' => 'Show Award']);
        Permission::create(['name' => 'Show Transfer']);
        Permission::create(['name' => 'Show Resignation']);
        Permission::create(['name' => 'Show Travel']);
        Permission::create(['name' => 'Show Promotion']);
        Permission::create(['name' => 'Manage System']);
        Permission::create(['name' => 'Manage Hr']);
        Permission::create(['name' => 'Manage Holiday']);
        Permission::create(['name' => 'Create Holiday']);
        Permission::create(['name' => 'Edit Holiday']);
        Permission::create(['name' => 'Delete Holiday']);
        Permission::create(['name' => 'Manage Project']);
        Permission::create(['name' => 'Create Project']);
        Permission::create(['name' => 'Edit Project']);
        Permission::create(['name' => 'Delete Project']);
        Permission::create(['name' => 'Manage Shift']);
        Permission::create(['name' => 'Create Shift']);
        Permission::create(['name' => 'Edit Shift']);
        Permission::create(['name' => 'Delete Shift']);
        //Permission::create(['name' => 'Overview']);
        Role::create(['name' => 'Super Admin']);
        // Role::create(['name' => 'Empolyee'])->givePermissionTo('Overview');
    }
}
